from weasyprint import HTML, CSS
from jinja2 import Template
import os
from datetime import datetime
from pathlib import Path

PDF_DIR = Path("generated_pdfs")
PDF_DIR.mkdir(parents=True, exist_ok=True)

def generate_loaner_agreement(data: dict, agreement_id: str) -> str:
    # clean blue-and-white template
    html_template = Template("""
    <html>
      <head>
        <style>
          body {
            font-family: 'Segoe UI', 'Helvetica Neue', sans-serif;
            margin: 40px;
            font-size: 14px;
            color: #1a1a1a;
            background-color: #fff;
          }
          h2 {
            color: #0033a0;
            border-bottom: 2px solid #0033a0;
            padding-bottom: 6px;
            margin-bottom: 24px;
          }
          .section {
            margin-bottom: 28px;
          }
          .label {
            font-weight: 600;
            display: inline-block;
            width: 200px;
            color: #0033a0;
          }
          .value {
            display: inline-block;
            color: #1a1a1a;
          }
          .signature {
            margin-top: 40px;
            border-top: 1px solid #aaa;
            width: 300px;
            text-align: center;
            padding-top: 10px;
            font-style: italic;
            color: #444;
          }
          .footer {
            margin-top: 60px;
            font-size: 12px;
            color: #888;
            border-top: 1px solid #e0e0e0;
            padding-top: 12px;
          }
        </style>
      </head>
      <body>
        <h2>Loaner Vehicle Agreement</h2>

        <div class="section">
          <div><span class="label">Customer Name:</span> <span class="value">{{ name }}</span></div>
          <div><span class="label">License Number:</span> <span class="value">{{ license_number }}</span></div>
          <div><span class="label">Insurance Verified:</span> <span class="value">{{ insurance_verified }}</span></div>
        </div>

        <div class="section">
          <div><span class="label">Vehicle:</span> <span class="value">{{ make }} {{ model }}</span></div>
          <div><span class="label">VIN:</span> <span class="value">{{ vin }}</span></div>
          <div><span class="label">Repair Order #:</span> <span class="value">{{ ro_number }}</span></div>
        </div>

        <div class="section">
          <div><span class="label">Agreement Date:</span> <span class="value">{{ date }}</span></div>
          <div class="signature">Digital Signature on File</div>
        </div>

        <div class="footer">
          This agreement was digitally generated by the Dealership Loaner Management Platform.
          For questions, contact your dealership representative.
        </div>

      </body>
    </html>
    """)

    rendered_html = html_template.render(
        name=data.get("name"),
        license_number=data.get("license_number"),
        make=data.get("make"),
        model=data.get("model"),
        vin=data.get("vin"),
        ro_number=data.get("ro_number"),
        insurance_verified="Yes" if data.get("insurance_verified") else "No",
        date=datetime.utcnow().strftime("%Y-%m-%d")
    )

    output_path = PDF_DIR / f"agreement_{agreement_id}.pdf"
    HTML(string=rendered_html).write_pdf(target=str(output_path))

    return str(output_path)
